## 8. Flathead sole
Status and catch specifications (t) of flathead sole in recent years. 
Biomass for each year corresponds to the projection given in the SAFE report issued in the preceding year. The OFL and ABC for `r year+1` and `r year+2` are those recommended by the Plan Team. 
Catch data are current through `r catch_data_date`.

```{r}
spp = c("flathead sole", "flathead")

specs %>% 
  dplyr::filter(stock %in% spp) %>% 
  tidyr::pivot_wider(names_from = measure, values_from = value) -> specs2
  
sum_tbl_bs(spp, bio, specs2)
```

*Changes from the previous assessment*  
This assessment was changed to a biennial cycle beginning with the 2014 assessment; this is a partial
assessment year. Changes to the input data in this analysis include updated catch information for 2020
and estimated catches for 2021 and 2022-2023. There were no changes to the assessment methodology.

*Spawning biomass and stock trends*  
Spawning biomass is projected to increase slightly in 2022 and in 2023. Age 3+ biomass is also projected
to have small increases in 2022 and 2023.

*Tier determination/Plan Team discussion and resulting ABCs and OFLs*  
The SSC has determined that reliable estimates of $B_{40\%}$, $F_{40\%}$, and $F_{35\%}$ exist for this stock, thereby qualifying flathead sole for management under Tier 3.
The current values of these reference points are $B_{40\%}$=81,463 t,$F_{40\%}$=0.37, and $F_{35\%}$=0.46. Because projected spawning biomass for 2022 (155,379 t) is above  $B_{40\%}$, flathead sole is in Tier 3a. The authors and Team recommend setting ABCs for 2022 and 2023 at the maximum permissible values under Tier 3a, which are 64,288 t and 65,988 t, respectively. 
The 2022 and 2023 OFLs under Tier 3a are 77,967 t and 80,034 t, respectively.

*Status determination*  
Flathead sole is not being subjected to overfishing, is not overfished, and is not approaching an overfished condition.


