## 2. Pacific cod  
Status and catch specifications (t) of Pacific cod in recent years. 
Biomass for each year corresponds to the projection given in the SAFE report issued in the preceding year. The OFL and ABC for `r year+1` and `r year+2` are those recommended by the Plan Team. 
Catch data are current through `r catch_data_date`.


```{r}
spp = c("pacific cod", "pcod")

specs %>% 
  dplyr::filter(stock %in% spp) %>% 
  tidyr::pivot_wider(names_from = measure, values_from = value) -> specs2
  

  bio %>%
    dplyr::filter(stock %in% spp) %>%
    dplyr::rename(!!nameit(.) := biomass) %>%
    dplyr::select(-type, -stock) %>%
    left_join(specs2, .) %>%
    dplyr::mutate(Area = case_when(area=="BS" ~ "Eastern Bering Sea",
                                  area=="AI" ~ "Aleutian Islands",
                                  TRUE ~ area),
                 Area = factor(Area, 
                              levels = c("BSAI", "Eastern Bering Sea", "Aleutian Islands"))) %>% 
    dplyr::select(Area, Year = year, dplyr::contains("biomass"),
                  OFL=ofl, ABC=abc, TAC=tac, Catch=catch) %>%
    # dplyr::arrange(dplyr::desc(Area)) %>%
    flextable::flextable() %>%
    flextable::merge_v(j=1) %>%
    flextable::colformat_num(j=2, big.mark = "") %>%
    flextable::hline(i=c(4)) %>%
    flextable::align(j=1, part="all") %>%
    flextable::valign(valign="bottom", part="header") %>%
    flextable::fix_border_issues() %>% 
  flextable::footnote(i = 1, j = 3,
            value = flextable::as_paragraph("Biomass shown for AI Pacific cod is survey biomass (Tier 5), not age 0+ biomass"),
            ref_symbols = c("*"),
            part = "header")
```

### Eastern Bering Sea Pacific cod 

*Changes from the previous assessment*  
The most important change from the previous assessment is that the accepted model is a weighted ensemble
of models rather than a single model. This approach has been recommended by the Groundfish Plan Teams
and the SSC and pursued in several previous assessments, but never approved by the BSAI Groundfish Plan
Team until now. Many changes have been made or considered in the stock assessment models since the
2020 assessment. Following the recommendation from a review by the Center for Independent Experts, an
ensemble consisting of four models and a corresponding set of model weights was presented in this year’s
assessment: Model 19.12a is the current base model, and the other three models each differed from the base
model with respect to a single, model-specific, feature. Model 19.12 included time-varying survey
catchability, Model 21.1 allowed for the possibility that survey selectivity declines at larger sizes (“domeshaped” selectivity), and Model 21.2 incorporated a fishery catch per unit effort (CPUE) index as a relative
measure of stock biomass. A fifth model (21.3), which estimated a constant that is added to the standard
deviation of each year’s log-scale abundance index, was considered in the preliminary assessment, but the
SSC suggested that it be omitted.
The following changes to the input data have been made in the EBS Pacific cod assessment.
1. Catches for 1991-2020 were updated, and a preliminary catch estimate for 2021 was
incorporated.
2. Using the vector autoregressive spatio-temporal (VAST) approach as before, but with some
adjustments to the set of hauls included in the data and an increase in the number of knots, the
EBS+NBS survey abundance time series was re-estimated through 2021.
3. Commercial fishery size compositions for 1991-2020 were updated, and a preliminary size
composition from the 2021 commercial fishery was incorporated.
4. The size composition data from the 2018 NBS survey were removed from the EBS+NBS survey
size composition for 2018 due to the nonstandard survey design used in the NBS that year, and
the size composition from the 2021 EBS+NBS survey was incorporated 
5. Using the VAST approach as before, but including otolith samples from the 2010, 2017, and 2019
NBS surveys, age compositions from the combined EBS+NBS survey time series were reestimated through 2019.
6. Long-term average weight-length parameters, and the time series of annual deviations therefrom,
were re-estimated through 2020, and preliminary estimates for 2021 were incorporated.
7. For one new model, a fishery CPUE time series, based on the VAST approach, was incorporated.

*Spawning biomass and stock trends*  
Recruitment is estimated to have been below average for the 2014-2017 year classes. Above average
recruitment is estimated for the 2018 year class. Estimated spawning biomass from the ensemble increased
from 2010 through 2019 to 315,000 t, and declined to 255,000 t in 2021. Spawning biomass is predicted to
increase to 260,000 t in 2022 with the recommended ABC. 

*Tier determination/Plan Team discussion and resulting ABCs and OFLs*  
This stock is assigned to Tier 3b for the determination of 2022 and 2023 ABCs and OFLs. The 2022
maxABC in this tier as calculated using the weighted average of the models in the ensemble is 153,383 t
and the projected 2023 maxABC is 151,709 t. The 2022 OFL from the weighted ensemble is 183,012 t. The
2023 projected OFL, given the respective 2022 catch from each individual model, is 180,909 t. Even though
a slightly elevated risk to the stock was identified due to environmental/ecosystem considerations, the Team did not recommend a reduction in the ABC.

*Status determination*  
EBS Pacific cod is not being subjected to overfishing, is not overfished, and is not approaching an
overfished condition.

### Aleutian Islands Pacific cod 

*Changes from previous assessment*  
This stock has been assessed separately from Eastern Bering Sea Pacific cod since 2013 and managed
separately since 2014. The stock has been managed under Tier 5 since it was first assessed separately. The
authors presented three alternative age-structured models this year. However, these models were not
accepted for management by the Team. Therefore, no changes were made to the methodology used for
recommending harvest specifications. Catch data from 1991-2020 were updated and preliminary catch data
for 2021 were included in the assessment, but these have no impact on recommended harvest specifications
under Tier 5.

*Spawning biomass and stock trends*  
After declining by more than 50% between 1991 and 2002, survey biomass has since stayed in the range of
50-90 kilotons. The 2018 Aleutians survey biomass estimate (81,272 t) was down approximately 4% from
the 2016 estimate (84,409 t). No Aleutian Island surveys for Pacific cod have been conducted since 2018.

*Tier determination/Plan Team discussion and resulting ABCs and OFLs*  
The Team recommends using the Tier 5 assessment again for setting 2022 and 2023 harvest
specifications. The Team’s recommended ABC is 20,600 t, and OFL is 27,400 t. The estimate of the
natural mortality rate is 0.34, which is unchanged from the previous assessment.

*Status determination*  
This stock is not being subjected to overfishing. It is not possible to determine whether this stock is
overfished or whether it is approaching an overfished condition because it is managed under Tier 5.


