## 4. Yellowfin sole  
Status and catch specifications (t) of yellowfin sole in recent years. 
Biomass for each year corresponds to the projection given in the SAFE report issued in the preceding year. The OFL and ABC for `r year+1` and `r year+2` are those recommended by the Plan Team. 
Catch data are current through `r catch_data_date`.

*Changes from the previous assessment*  
Changes to the input data include:
1. The 2020 fishery age composition was added.
2. The estimate of the total catch made through the end of 2020 was updated as reported by the NMFS
Alaska Regional office. The catch through the end of 2021 was estimated to be 108,086 t. Catch
for the 2022 and 2023 projections were assumed to be equal to the mean of the past 5 years (126,929
t).
3. The 2021 NMFS survey biomass estimate and standard error were included.
The authors and Team recommend retaining the current base model (18.2) for use in setting 2022 and 2023
harvest specifications.

*Spawning biomass and stock trends*  
The projected female spawning biomass estimate for 2022 is 899,129 t, which is 1.81 × BMSY. This is a 10%
decrease from last year’s 2022 estimate (996,044 t). A general slow decline in spawning biomass has
prevailed for the most part since 1995.

*Tier determination/Plan Team discussion and resulting ABCs and OFLs*  
The lead author presented the results from three assessment models. One is last year’s model (18.2); one is
the same aslast year’s model, except with VAST estimated survey biomass for the EBS (18.2a); and another
with VAST estimated survey biomass for both the EBS and NBS (18.2b). The author recommended use of
model 18.2 for this year’s management and the Team concurred. The risk table indicated “substantially
increased concerns” (level 2) for all but the fishery performance category (which was scored as level 1),
and the Team concurred with the author’s recommendation of reducing ABC to the average of the Tier 1
and Tier 3 maximum ABCs. This corresponds to a 24% reduction from the Tier 1a maximum ABC.

The SSC has determined that reliable estimates of BMSY and the probability density function for FMSY exist for this stock. 
The estimate of BMSY from the present assessment is 495,904 t, and projected spawning biomass for 2022 is 899,126 t, meaning that yellowfin sole qualify for management under Tier 1a. 
Corresponding to the approach used in recent years, the 1978-2015 age-1 recruitments (and corresponding spawning biomass estimates) were used this year to determine the Tier 1 harvest recommendations. This provided a maximum permissible ABC harvest ratio (the harmonic mean of the FMSY harvest ratio) of 0.143. 
The current value of the OFL harvest ratio (the arithmetic mean of the FMSY ratio) is 0.152. 
The product of the maximum permissible ABC harvest ratio and the geometric mean of the 2022 biomass estimate produced the 2022 maximum ABC of 354,014 t. 
The authors and Team recommend reducing the 2022 ABC to 269,649 t. 
The corresponding product using the OFL harvest ratio produces the 2022 OFL of 377,071 t. 
For 2023, the corresponding quantities are a maximum ABC of 358,675 t, reduced to an ABC of 274,787 t, and an OFL of 382,035 t, respectively.

*Status determination*  
Yellowfin sole is not being subjected to overfishing, is not overfished, and is not approaching an overfished
condition.



